# Generated by Django 5.2 on 2025-04-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_id", models.IntegerField()),
                ("name", models.CharField(max_length=100, unique="true")),
                ("kind", models.CharField(max_length=50, unique="true")),
            ],
        ),
    ]
