# Generated by Django 5.2 on 2025-04-11 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="kind",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
