# Generated by Django 5.2 on 2025-04-11 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_score_id_alter_score_kind_alter_score_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonPrevious",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=250)),
                ("slug", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=250)),
                ("slug", models.CharField(max_length=20)),
                (
                    "previous",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.seasonprevious",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("short", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.season"
                    ),
                ),
            ],
        ),
    ]
