# Generated by Django 5.2 on 2025-04-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_player_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="player",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.player"
            ),
            preserve_default=False,
        ),
    ]
