# Generated by Django 5.2 on 2025-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_seasonprevious_season_seasonround"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonround",
            name="round_id",
            field=models.IntegerField(default=0),
        ),
    ]
