# Generated by Django 5.2 on 2025-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_stat_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
