# Generated by Django 5.2 on 2025-04-11 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_seasonround_round_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("short", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("start", models.IntegerField(default=0)),
                ("end", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="GameTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team_id", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=10)),
                ("score", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_id", models.IntegerField(default=0)),
                ("date", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=20)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activeevent",
                    ),
                ),
                (
                    "away",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away",
                        to="api.gameteam",
                    ),
                ),
                (
                    "home",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home",
                        to="api.gameteam",
                    ),
                ),
            ],
        ),
    ]
