# Generated by Django 5.2 on 2025-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_activeevent_gameteam_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameteam",
            name="score",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
