# Generated by Django 5.2 on 2025-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_competition_playeranalysisranking_playerprediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status_info',
            field=models.TextField(null=True),
        ),
    ]
