version: '3.9'

services:
  fantasy-db:
    image: postgres:15.3
    container_name: fantasy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - fantasy-service-net

networks:
  fantasy-service-net:

volumes:
  postgres_data:
